version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/webappbackend

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1200
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1200
      runas: root
  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 1200
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 1200
      runas: root
  